name:       runmany
version:    0.1.3
synopsis:   Run multiple commands, interleaving output and errors
github:     jwiegley/runmany
author:     John Wiegley
maintainer: johnw@newartisans.com
category:   System, Data, Nix
license:    BSD3

description:
  Run multiple commands, interleaving output and errors

ghc-options:
  - -Wall

executables:
  runmany:
    main: Main.hs
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - base >=4.9 && <4.13
      - optparse-applicative >=0.12 && <0.14
      - stm
      - async
      - bytestring
      - process
